version: 2
jobs:
  test:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run test
  coverage:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum "package.json" }}
            - dependency-cache-
      - run: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run: npm run coverage

workflows:
  version: 2
  commit:
    jobs:
      - test
      - coverage:
          requires:
            - test
